parameters:
- name: listOfStrings
  type: object
  default:
  - one
  - two
- name: listOfFruits
  type: object
  default:
  - fruitName: 'apple'
    colors: ['red','green']
  - fruitName: 'lemon'
    colors: ['yellow']

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
    displayName: 'loop parameters.listOfStrings'

- ${{ each fruit in parameters.listOfFruits }} :
  - ${{ each fruitColor in fruit.colors}} :
    - script: echo ${{ fruit.fruitName}} ${{ fruitColor }}
      displayName: 'loop parameters.listOfFruits'
