# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: age
  type: number
  default: 1888888
- name: myNumber
  type: number
  default: 2
  values:
  - 1
  - 2
  - 4
  - 8
  - 16
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
    nested:
      one: apple
      two: pear
      count: 3
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two
- name: listOfStrings
  type: object
  default:
  - one
  - two
- name: listOfFruits
  type: object
  default:
  - fruitName: 'apple'
    colors: ['red','green']
  - fruitName: 'lemon'
    colors: ['yellow']
- name: myJobList
  type: jobList
  default: 
    - job: job1
      steps:
        - script: echo joblist job 1
    - job: job2
      steps:
        - script: echo joblist job 2
    - job: job3
      steps:
        - script: echo joblist job 3
- name: myStageList
  type: stageList
  default: 
    - stage: stageList1
      jobs:
      - job: stageList1Job
        steps:
        - script: echo stageList1Job
    - stage: stageList2
      jobs:
      - job: stageList2Job
        steps:
        - script: echo stageList2Job
    - stage: stageList3
      jobs:
      - job: stageList3Job
        steps:
        - script: echo stageList3Job

variables:
- name: age
  value: 133333 

trigger:
# - main

stages:
- stage: VSBuildStage
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: VSBuildJob
    steps:
    - ${{ parameters.myStep }}

    - ${{ each value in parameters.listOfStrings }}:
      - script: echo ${{ value }}
        displayName: 'loop parameters.listOfStrings'

    - ${{ each fruit in parameters.listOfFruits }}:
      - ${{ each fruitColor in fruit.colors}} :
        - script: echo ${{ fruit.fruitName}} ${{ fruitColor }}
          displayName: 'loop parameters.listOfFruits'

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - script: |
        echo building $(Build.BuildNumber) with ${{ parameters.age }}
      displayName: 'test script 1'

    - task: PowerShell@2
      displayName: 'test script 2'
      inputs:
        targetType: 'inline'
        script: 'Write-Host ${{ parameters.age }}'

    - task: PowerShell@2
      displayName: 'test script 3'
      inputs:
        targetType: 'inline'
        script: 'Write-Host $env:NAME'

    - task: Bash@3
      displayName: 'test Bash 4'
      inputs:
        targetType: 'inline'
        script: 'echo $(name)'

    - task: Bash@3
      displayName: 'test Bash 5'
      inputs:
        targetType: 'inline'
        script: 'echo ${{ parameters.age }}'

    - task: Bash@3
      displayName: 'test Bash 6'
      inputs:
        targetType: 'inline'
        script: 'echo ${{ variables.age }}'

  - job: stepList
    steps: ${{ parameters.mySteplist }}

  - job: myStep
    steps:
      - ${{ parameters.myStep }}

  - ${{ parameters.myJobList}}

- ${{ parameters.myStageList }}