# File: azure-pipelines.yml
trigger:
- main

extends:
  template: simple-param.yml
  parameters:
    yesNo: true # set to a non-boolean value to have the build fail
    mySteplist:  
      - bash: echo Test #Passes
        displayName: succeed
      - bash: echo "Test"
        displayName: succeed
      - task: CmdLine@2
        inputs:
          script: echo "Script Test"
      - script: echo "Script Test"
      