# trigger:
# - main

trigger: none

extends:
  template: simple-param.yml
  parameters:
    yesNo: true
    DependsOnList1: [job1, job2]
    DependsOnList2: [job3, job4]
    mySteplist:  
      - bash: echo Test
        displayName: succeed
      - bash: echo "Test"
        displayName: succeed
      - task: CmdLine@2
        inputs:
          script: echo "Script Test"
      - script: echo "Script Test"
    myJobList1: 
      - job: job1
        steps:
          - script: echo joblist job 3
      - job: job2
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: |
              npm run work
            displayName: 'npm install and build'
    myJobList2: 
      - job: job3
        steps:
          - script: echo joblist job 1
      - job: job4
        steps:
          - script: echo joblist job 2
