trigger:
- main

# trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: Foo1
  steps:
  - script: echo Hello!

- job: Foo2
  steps:
  - script: echo Hello!

- job: Foo3
  steps:
  - script: echo Hello!
- job: Foo4
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm run work
      displayName: 'npm install and build'

- job: Bar1
  dependsOn: [Foo1, Foo2, Foo3, Foo4]
  steps:
  - script: echo running Bar1

- job: Bar2
  dependsOn: Foo2
  steps:
  - script: echo running Bar2
