parameters:
- name: yesNo
  type: boolean
  default: false

- name: mySteplist 
  type: stepList
  default: []
  
stages:
- stage: secure_buildstage
  pool:
    vmImage: windows-latest
  jobs:
  - job: secure_buildjob
    steps:
      - script: echo This happens after code  ${{ parameters.yesNo }}
        displayName: 'test paramters yesNo'
  - job: mySteplist
    steps: ${{ parameters.mySteplist }}

    

      
