# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: listOfStrings
  type: object
  default:
  - one
  - two
- name: listOfFruits
  type: object
  default:
  - fruitName: 'apple'
    colors: ['red','green']
  - fruitName: 'lemon'
    colors: ['yellow']

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- ${{ each value in parameters.listOfStrings }}:
      - script: echo ${{ value }}
        displayName: 'loop parameters.listOfStrings'

- ${{ each fruit in parameters.listOfFruits }}:
  - ${{ each fruitColor in fruit.colors}} :
    - script: echo ${{ fruit.fruitName}} ${{ fruitColor }}
      displayName: 'loop parameters.listOfFruits'


